format = "$character$directory$custom "

[character]
success_symbol = "[➜](bold green)"
error_symbol   = "[➜](bold red)"

[directory]
style = "cyan"

[custom.git_branch]
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
command = '''
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
if git diff --quiet --ignore-submodules HEAD; then
  # clean -> cyan branch
  echo "$(printf '\033[37m')git:($(printf '\033[36m')$branch$(printf '\033[0m')$(printf '\033[37m'))$(printf '\033[0m')"
else
  # dirty -> red branch
  echo "$(printf '\033[37m')git:($(printf '\033[31m')$branch$(printf '\033[0m')$(printf '\033[37m'))$(printf '\033[0m')"
fi
'''
style = ""
format = "$output"
